# Generated by Django 5.1.4 on 2025-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("matchup", models.CharField(max_length=255)),
                ("yahoo_total", models.FloatField()),
                ("yahoo_spread", models.FloatField()),
                ("predicted_total", models.FloatField()),
                ("predicted_spread", models.FloatField()),
                ("favored_team", models.CharField(max_length=100)),
            ],
        ),
    ]
